apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: nfs
  nfs:
    path: /srv/exports/vol1
    server: bluster-1-001.jkb.io
